INSERT INTO
     user_user (id,username,email,password,first_name,last_name,is_tutor)
VALUES (1,'manhdd','manhdd@gmail.com','abc123','Manh','Duc','true'),
                                (2,'HungMM','HungMM@gmail.com','abc123','Hung','Ma','false'),
                                (3,'HoangNN','HoangNN@gmail.com','abc123','Hoang','Nguyen','true'),
                                (4,'KimK','Kim@gmail.com','abc123','Kim','Kim','false'),
                                (5,'GiangPM','GiangPM@gmail.com','abc123','Giang','Phan','true'),
                                (6,'TruongNT','TruongNT@gmail.com','abc123','Truong','Nguyen','false'),
                                (7,'KienMP','KienMP@gmail.com','abc123','Kien','Phan','true'),
                                (8,'TrungTT','TrungTT@gmail.com','abc123','Trung','Tran','false'),
                                (9,'HaPM','HaPM@gmail.com','abc123','Ha','Pham','true'),
                                (10,'LinhHH','LinhHH@gmail.com','abc123','Linh','Ho','false'),
                                (11,'ThanhDM','ThanhDM@gmail.com','abc123','Thanh','Do','true'),
                                (12,'TrinhLT','TrinhLT@gmail.com','abc123','Trinh','Le','false'),
                                (13,'HopDT','HopDT@gmail.com','abc123','Hop','Dang','true');

INSERT INTO user_subject VALUES (1,'Toan 1','Toan lop 1'),
                                (2,'Toan 2','Toan lop 1'),
                                (3,'Toan 3','Toan lop 1'),
                                (4,'Toan 4','Toan lop 1'),
                                (5,'Toan 5','Toan lop 1'),
                                (6,'Toan 6','Toan lop 1'),
                                (7,'Toan 7','Toan lop 1'),
                                (8,'Toan 8','Toan lop 1'),
                                (9,'Toan 9','Toan lop 1'),
                                (10,'Toan 10','Toan lop 1'),
                                (11,'Toan 11','Toan lop 1'),
                                (12,'Toan 12','Toan lop 1'),
                                (13,'Van 1','Van lop 1'),
                                (14,'Van 2','Van lop 2'),
                                (15,'Van 3','Van lop 3'),
                                (16,'Van 4','Van lop 4'),
                                (17,'Van 5','Van lop 5'),
                                (18,'Van 6','Van lop 6'),
                                (19,'Van 7','Van lop 7'),
                                (20,'Van 8','Van lop 8'),
                                (21,'Van 9','Van lop 9'),
                                (22,'Van 10','Van lop 10'),
                                (23,'Van 11','Van lop 11'),
                                (24,'Van 12','Van lop 12'),
                                (25,'Khoa hoc 4','Khoa hoc lop 4'),
                                (26,'Khoa hoc 5','Khoa hoc lop 5'),
                                (27,'Khoa hoc 6','Khoa hoc lop 6'),
                                (28,'Khoa hoc 7','Khoa hoc lop 7'),
                                (29,'Khoa hoc 8','Khoa hoc lop 8'),
                                (30,'Khoa hoc 9','Khoa hoc lop 9'),
                                (31,'Khoa hoc 10','Khoa hoc lop 10'),
                                (32,'Khoa hoc 11','Khoa hoc lop 11');

INSERT INTO user_session VALUES (11,'Monday',1),
                                (12,'Monday',2),
                                (13,'Monday',3),
                                (21,'Tuesday',1),
                                (22,'Tuesday',2),
                                (23,'Tuesday',3),
                                (31,'Wendnesday',1),
                                (32,'Wendnesday',2),
                                (33,'Wendnesday',3),
                                (41,'Thursday',1),
                                (42,'Thursday',2),
                                (43,'Thursday',3),
                                (51,'Friday',1),
                                (52,'Friday',2),
                                (53,'Friday',3),
                                (61,'Saturday',1),
                                (62,'Saturday',2),
                                (63,'Saturday',3),
                                (71,'Sunday',1),
                                (72,'Sunday',2),
                                (73,'Sunday',3);

INSERT INTO user_lesson VALUES (1,1,1,'Day toan lop 1','cong tru co ban',11,'2023-01-10'),
                                (2,3,3,'Day toan lop 3','bang cuu chuong',22,'2023-04-04'),
                                (3,4,5,'Day toan lop 4','phep chia co du',33,'2023-05-05');