# Generated by Django 4.2 on 2023-04-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='img_url',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='user',
            name='img_url',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
