# Generated by Django 4.2 on 2023-04-20 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_news_img_url_user_img_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='img_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='img_url',
        ),
    ]
